spring:
  application:
    name: email-notify
  mail:
    host: smtp.gmail.com
    username: bakaraka01@gmail.com
    password: scgjndkfpjqklcob
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


server:
  port: 8081


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
